package com.personal.assistant.core.domain

import com.personal.assistant.core.ai.TaskDraft
import com.personal.assistant.core.model.Task
import com.personal.assistant.core.report.DailyReport
import com.personal.assistant.core.report.MonthlyReport
import com.personal.assistant.core.report.TaskTotals
import com.personal.assistant.core.report.WeeklyReport
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.util.Locale

/**
 * Builds the assistant's replies.
 *
 * The wording is produced here, from database values, instead of being generated by the model. That is
 * the other half of the reliability rule: if the model wrote the confirmation, the number in the
 * sentence and the number in the database could disagree, and the user would have no way to tell which
 * one the reminder will use.
 *
 * Any assumption the parser made is stated in the reply rather than hidden, so a wrong guess is
 * visible immediately instead of surfacing as a missed alarm.
 */
class ResponseComposer(private val locale: Locale = Locale.ENGLISH) {

    private val timeFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("h:mm a", locale)
    private val dayFormat: DateTimeFormatter = DateTimeFormatter.ofPattern("d MMMM", locale)

    fun time(value: LocalTime): String = value.format(timeFormat)

    fun day(date: LocalDate, today: LocalDate): String = when (date) {
        today -> "today"
        today.plusDays(1) -> "tomorrow"
        today.minusDays(1) -> "yesterday"
        else ->
            if (date.year == today.year) {
                "${date.dayOfWeek.getDisplayName(TextStyle.FULL, locale)}, ${date.format(dayFormat)}"
            } else {
                "${date.format(dayFormat)} ${date.year}"
            }
    }

    /** Confirmation for a task that has just been saved. */
    fun taskCreated(task: Task, today: LocalDate, draft: TaskDraft? = null): String = buildString {
        append("Scheduled \"${task.title}\" for ${day(task.date, today)}")
        task.startTime?.let { start ->
            append(" at ${time(start)}")
            task.endTime?.let { append(" - ${time(it)}") }
        }
        append(".")
        task.reminderMinutes?.takeIf { task.startTime != null }?.let { lead ->
            append(" Reminder ${TimeTracker.format(lead)} before")
            task.reminderAt?.let { append(" (${time(it.toLocalTime())})") }
            append(".")
        }
        if (task.startTime == null && task.durationMinutes != null) {
            append(" Blocked out ${TimeTracker.format(task.durationMinutes)}; tell me a time and I'll set a reminder.")
        }
        draft?.let { appendAssumptions(it) }
    }

    /** Spells out every guess, so a wrong one can be corrected before the alarm matters. */
    private fun StringBuilder.appendAssumptions(draft: TaskDraft) {
        val notes = mutableListOf<String>()
        if (draft.meridiemAssumed) notes += "I read the time as afternoon/evening"
        if (draft.dateDirectionAssumed) notes += "I read the day as the one coming up"
        if (draft.dateInferred) notes += "no day was given, so I used the next time that hour comes round"
        if (notes.isNotEmpty()) {
            append(" (")
            append(notes.joinToString("; "))
            append(" -- tap Edit to change.)")
        }
    }

    fun rescheduled(task: Task, today: LocalDate): String = buildString {
        append("Moved \"${task.title}\" to ${day(task.date, today)}")
        task.startTime?.let { append(" at ${time(it)}") }
        append(". Reminders updated.")
    }

    fun statusChanged(task: Task): String = when (task.status) {
        com.personal.assistant.core.model.TaskStatus.COMPLETED -> "Marked \"${task.title}\" complete."
        com.personal.assistant.core.model.TaskStatus.PARTIALLY_COMPLETED ->
            "Recorded \"${task.title}\" as partly done (${task.progress}%)."
        com.personal.assistant.core.model.TaskStatus.CANCELLED -> "Cancelled \"${task.title}\"."
        com.personal.assistant.core.model.TaskStatus.SKIPPED -> "Skipped \"${task.title}\"."
        com.personal.assistant.core.model.TaskStatus.POSTPONED -> "Postponed \"${task.title}\"."
        com.personal.assistant.core.model.TaskStatus.MISSED -> "Recorded \"${task.title}\" as missed."
        else -> "Updated \"${task.title}\" to ${task.status.name.lowercase().replace('_', ' ')}."
    }

    fun progressRecorded(task: Task): String =
        "\"${task.title}\" is at ${task.progress}%." +
            if (task.progress >= 100) " Nice -- marked complete." else ""

    fun conflictWarning(conflicts: List<Conflict>): String = buildString {
        appendLine(conflicts.first().describe())
        append("Keep both, or move one?")
    }

    fun ambiguousReference(candidates: List<Task>, today: LocalDate): String = buildString {
        appendLine("I found ${candidates.size} tasks that match. Which one?")
        candidates.take(5).forEachIndexed { index, task ->
            append("${index + 1}. ${task.title} - ${day(task.date, today)}")
            task.startTime?.let { append(" at ${time(it)}") }
            appendLine()
        }
    }.trimEnd()

    fun nothingFound(what: String): String = "I couldn't find any $what."

    fun plan(date: LocalDate, tasks: List<Task>, today: LocalDate): String {
        if (tasks.isEmpty()) return "Nothing scheduled for ${day(date, today)}."
        val ordered = tasks.sortedWith(compareBy({ it.startTime ?: LocalTime.MAX }, { it.title }))
        return buildString {
            appendLine("Plan for ${day(date, today)}:")
            for (task in ordered) {
                val when_ = task.startTime?.let { time(it) } ?: "any time"
                append("$when_ - ${task.title}")
                if (task.status.isActive) append(" (in progress, ${task.progress}%)")
                if (task.status == com.personal.assistant.core.model.TaskStatus.COMPLETED) append(" (done)")
                appendLine()
            }
        }.trimEnd()
    }

    fun taskList(title: String, tasks: List<Task>, today: LocalDate): String {
        if (tasks.isEmpty()) return "Nothing to show for $title."
        return buildString {
            appendLine("$title:")
            for (task in tasks.take(20)) {
                append("- ${task.title}, ${day(task.date, today)}")
                task.startTime?.let { append(" at ${time(it)}") }
                appendLine()
            }
            if (tasks.size > 20) append("...and ${tasks.size - 20} more")
        }.trimEnd()
    }

    fun dailyReport(report: DailyReport, today: LocalDate): String = buildString {
        appendLine("${day(report.date, today).replaceFirstChar { it.titlecase(locale) }}")
        appendLine()
        appendTotals(report.totals)
        appendLine("Planned time: ${TimeTracker.format(report.plannedMinutes)}")
        append("Tracked time: ${TimeTracker.format(report.trackedMinutes)}")
    }

    fun weeklyReport(report: WeeklyReport): String = buildString {
        appendLine("Week of ${report.range.start} to ${report.range.end}")
        appendLine()
        appendTotals(report.totals)
        appendLine("Planned time: ${TimeTracker.format(report.plannedMinutes)}")
        append("Tracked time: ${TimeTracker.format(report.trackedMinutes)}")
    }

    fun monthlyReport(report: MonthlyReport): String = buildString {
        appendLine("${report.range.start.month.getDisplayName(TextStyle.FULL, locale)} ${report.range.start.year}")
        appendLine()
        appendTotals(report.totals)
        appendLine("Planned time: ${TimeTracker.format(report.plannedMinutes)}")
        appendLine("Tracked time: ${TimeTracker.format(report.trackedMinutes)}")
        report.categories.firstOrNull()?.let {
            appendLine("Most time on: ${it.label} (${TimeTracker.format(it.minutes)})")
        }
        report.mostActiveDays.firstOrNull()?.let {
            append("Most productive day: ${it.date} (${it.totals.completed} completed)")
        }
    }

    private fun StringBuilder.appendTotals(totals: TaskTotals) {
        appendLine("Tasks: ${totals.total}")
        if (totals.completed > 0) appendLine("Completed: ${totals.completed}")
        if (totals.partial > 0) appendLine("Partial: ${totals.partial}")
        if (totals.inProgress > 0) appendLine("In progress: ${totals.inProgress}")
        if (totals.pending > 0) appendLine("Pending: ${totals.pending}")
        if (totals.missed > 0) appendLine("Missed: ${totals.missed}")
        if (totals.cancelled > 0) appendLine("Cancelled: ${totals.cancelled}")
        appendLine("Completion: ${formatRate(totals.completionRate)}")
    }

    fun formatRate(rate: Double): String {
        val rounded = Math.round(rate * 10.0) / 10.0
        return if (rounded % 1.0 == 0.0) "${rounded.toInt()}%" else "$rounded%"
    }

    fun timeSpent(label: String, minutes: Int): String =
        if (minutes == 0) "No tracked time for $label yet." else "You spent ${TimeTracker.format(minutes)} on $label."

    fun startFollowUp(task: Task): String = "\"${task.title}\" is starting now. Are you starting it?"

    fun completionFollowUp(task: Task, composer: ResponseComposer = this): String = buildString {
        append("You planned \"${task.title}\"")
        val start = task.startTime
        val end = task.endTime
        if (start != null && end != null) append(" from ${composer.time(start)} to ${composer.time(end)}")
        append(". Did you complete it?")
    }

    fun missedFollowUp(task: Task, today: LocalDate): String =
        "\"${task.title}\" on ${day(task.date, today)} wasn't marked done. Move it to tomorrow?"

    fun dailySummary(report: DailyReport, today: LocalDate): String = buildString {
        appendLine("Daily summary")
        appendLine()
        appendLine("Planned: ${report.totals.total}")
        appendLine("Completed: ${report.totals.completed}")
        if (report.totals.partial > 0) appendLine("Partial: ${report.totals.partial}")
        if (report.totals.missed > 0) appendLine("Missed: ${report.totals.missed}")
        appendLine("Completion rate: ${formatRate(report.totals.completionRate)}")
        if (report.trackedMinutes > 0) {
            append("You worked for ${TimeTracker.format(report.trackedMinutes)} today.")
        } else {
            append("No tracked time recorded today.")
        }
    }

    fun memorySaved(content: String): String =
        "Noted: \"$content\". You can view or delete it under Memory."

    /** Used by the chat when the model is unavailable, so the fallback is never silent. */
    fun modelUnavailableNotice(): String =
        "The language model isn't loaded, so I'm using the built-in parser. " +
            "Everything still works -- tasks, reminders, reports."

    fun clock(at: LocalDateTime): String = at.format(timeFormat)
}
